version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - type: bind
        source: ./
        target: /var/www
    command: >
      bash -c "chown -R www-data:www-data /var/www/database &&
               chmod -R 775 /var/www/database &&
               php-fpm"
    networks:
      - laravel_net

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - type: bind
        source: ./
        target: /var/www
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./
        target: /var/www
      - type: bind
        source: ./docker/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
    networks:
      - laravel_net

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  dbdata: 